POST http://localhost:3001/api/transactions
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJpZCI6IjYzYmJmYjdkMDU2MzI0NTFjYzg4OTQ2NyIsImlhdCI6MTY3MzM1NDc0MH0.iQz6XGeA0ZGup5FeMmMK8YarzTyPjyoA0hTQhe1yl0g

{
    "reference": "milk",
    "amount": 10,
    "userid": "63bbfb7d05632451cc889467"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json


{
    "username": "iziew",
    "name": "Izie Wood",
    "balance": 10
}

###
DELETE http://localhost:3001/api/users/63bc1a3a26b164d97d2d3a4f
DELETE http://localhost:3001/api/users/63b9d2241bf3e986382ce341


###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "loop",
    "name": "kooks",
    "password": "kkoookal",
    "allowance": 10
}
###
DELETE http://localhost:3001/api/transactions/63bd70b83336441352ed06cf
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbmciLCJpZCI6IjYzYmJmYjdkMDU2MzI0NTFjYzg4OTQ2NyIsImlhdCI6MTY3MzM1NDc0MH0.iQz6XGeA0ZGup5FeMmMK8YarzTyPjyoA0hTQhe1yl0g

###
PUT http://localhost:3001/api/users/63bbfb7d05632451cc889467
Content-Type: application/json

{   
    "transactions": []
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{   "username": "testing",
    "password": "testing123"
}

###
GET http://localhost:3001/api/transactions